/*
======================================================
Branching Out Heritage v2
Database Schema
======================================================
*/


-- FAMILY TREES

create table if not exists trees (

    id bigint generated by default as identity primary key,

    name text not null,

    description text,

    created_at timestamp default now()

);



-- PEOPLE

create table if not exists people (

    id bigint generated by default as identity primary key,

    tree_id bigint references trees(id),

    first_name text,

    middle_name text,

    last_name text,

    birth_date date,

    death_date date,

    gender text,

    biography text,

    photo_url text,

    created_at timestamp default now()

);



-- RELATIONSHIPS

create table if not exists relationships (

    id bigint generated by default as identity primary key,

    tree_id bigint references trees(id),

    person_one bigint references people(id),

    person_two bigint references people(id),

    relationship_type text,

    created_at timestamp default now()

);



-- LIFE EVENTS

create table if not exists events (

    id bigint generated by default as identity primary key,

    person_id bigint references people(id),

    event_type text,

    event_date date,

    location text,

    description text,

    created_at timestamp default now()

);



-- SOURCES

create table if not exists sources (

    id bigint generated by default as identity primary key,

    person_id bigint references people(id),

    title text,

    source_type text,

    url text,

    notes text,

    created_at timestamp default now()

);



-- PHOTOS

create table if not exists photos (

    id bigint generated by default as identity primary key,

    person_id bigint references people(id),

    image_url text,

    caption text,

    created_at timestamp default now()

);



-- DOCUMENTS

create table if not exists documents (

    id bigint generated by default as identity primary key,

    person_id bigint references people(id),

    title text,

    document_url text,

    document_type text,

    created_at timestamp default now()

);